# Generated by Django 3.2 on 2021-05-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('auth_name', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=128)),
                ('category', models.CharField(choices=[('G', 'General'), ('S', 'Sports'), ('T', 'Trending'), ('P', 'Politics')], default='None', max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
