# Generated by Django 3.2 on 2021-05-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_register', '0003_remove_blog_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='auth_name',
            field=models.CharField(default='not_defined', max_length=100),
            preserve_default=False,
        ),
    ]
